# Generated by Django 6.0.5 on 2026-05-29 00:03


from django.db import migrations, models



class Migration(migrations.Migration):


    dependencies = [

        ('users', '0001_initial'),

    ]


    operations = [

        migrations.AlterField(

            model_name='user',

            name='phone',

            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Телефон'),

        ),

    ]
